# This workflow runs update-readme.py which updates README.md file.

name: Update readme # GitHub Actions 탭에서 확인할 수 있는 액션 이름

on: # jobs가 실행되어야 하는 상황 정의
  push:
    branches: [ main ] # master 브랜치에 push가 발생했을 때
  pull_request:
    branches: [ main ] # master 브랜치에 pull request가 발생했을 때

jobs: # 실제 실행될 내용
  build:
    runs-on: macOS 26.1 # 빌드 환경
    steps:
    - uses: actions/checkout@v3 # checkout
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v3 # setup-python
      with:
        python-version: "3.9" # 3.10버전 파이썬 사용
    - name: Install dependencies # 1) 스크립트에 필요한 dependency 설치
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode 
    - name: Run update-readme.py # 2) update-readme.py 실행
      run: |
        python update-readme.py
    - name: Commit changes # 3) 추가된 파일 commit
      run: |
        git config --global user.name 'Doyeop_Lee' # 유저명
        git config --global user.email 'gunx99@a.ut.ac.kr' # 유저 이메일
        git add -A
        git commit -am "auto-update README.md" # 커밋 메시지
    - name: Push changes # 4) master에 푸시
      run: |
        git push
